### PR TITLE
Argument parsing added using docopt

### PR DESCRIPTION
**Pull request by bookdude13**
Addresses #4.

### CODE REVIEW

**Comment by rjayatilleka** [comment]
I would do the arg parse section more like this:

```
// You don't need type annotation on command in the actual code.
let command :  fn(Args) -> Result<(), Error> = match (env::args().nth(1).unwrap()) {
    "init" => run_init,
    "new-user" => run_new_user,
    "identify" => run_identify,
    ...
}

let result = command(args);
```

Changes:

1. Get rid of subcommands like `user new`, `user id`. It just makes things more complicated. Feel free to name them as you think best. Use dashes for multiple words.
2. After parsing into an Args struct with docopt, match directly on the second argument. This is ok since Docopt ensures that the arguments fit the usage.
3. Move actual code into their own functions `run_init`, `run_new_user`, etc. -- I shouldn't need to say this.
4. Change expects to unwraps. If we got the right command, it should have the proper args as well (or docopt would have thrown a parse error).

Pros:

1. Get rid of ArgumentNotFound error.
2. Result is no longer mutable, and it didn't need to be.
3. The choice of command is a lot easier to read.

Cons:

1. Using docopt for argument validation and parsing, but then switching on the subcommand arg directly is inconsistent.

**Comment by rjayatilleka** [comment]
What do you think?

**Comment by bookdude13** [comment]
I like this a lot better. Forgot about returning a function. Docopt handles a lot of errors that I was trying to handle, and this approach is cleaner. The direct match on the argument is a bit inconsistent, but docopt is mostly used to validate and parse the argument(s), not necessarily use them.

**Comment by bookdude13** [comment]
Turns out the compiler doesn't like it when I don't explicitly specify the type of `command`. This looks a lot cleaner. I left out the final piece of the `add_user` implementation until that pull request gets reviewed.

**Comment by rjayatilleka** [comment]
Get rid of all those `// Safe because of docopt` comments, and add one comment right after the docopt parse saying that `// Below Unwrap()'s are all safe within Docopt's usage rules.`

After that, LGTM

**Pull request merged**
